//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatTable()
        {
            this.FeedCatTable = new HashSet<FeedCatTable>();
            this.TraitCat = new HashSet<TraitCat>();
        }
    
        public int idCat { get; set; }
        public string CatName { get; set; }
        public int idBreed { get; set; }
        public System.DateTime Birthday { get; set; }
        public int idGender { get; set; }
        public string Photo { get; set; }
    
        public virtual BreedTable BreedTable { get; set; }
        public virtual GenderTable GenderTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedCatTable> FeedCatTable { get; set; }
        public virtual PassportTable PassportTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraitCat> TraitCat { get; set; }
    }
}
