//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedCatTable
    {
        public int idFeedCat { get; set; }
        public int idCat { get; set; }
        public int idFeed { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual CatTable CatTable { get; set; }
        public virtual FeedTable FeedTable { get; set; }
    }
}
