//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int idUser { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Login { get; set; }
        public int Password { get; set; }
        public int idGender { get; set; }
        public int idRole { get; set; }
    
        public virtual GenderTable GenderTable { get; set; }
        public virtual RoleTable RoleTable { get; set; }
    }
}
