//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userphoto
    {
        public int idPhoto { get; set; }
        public int idUser { get; set; }
        public byte[] photoBinary { get; set; }
        public string photoPath { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
